# Generated by Django 5.0.1 on 2024-01-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('anexo', models.ImageField(upload_to='')),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('categoria', models.IntegerField(choices=[(1, 'Software'), (2, 'Hardware')])),
                ('encerrado_em', models.DateField(null=True)),
            ],
        ),
    ]
