# Generated by Django 5.0.1 on 2024-01-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamados',
            name='anexo',
        ),
    ]
